-- MySQL Script generated by MySQL Workbench
-- 05/26/17 23:00:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`services` ;

CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`company_service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`company_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_idx` (`company_id` ASC),
  INDEX `fk_service_idx` (`service_id` ASC),
  CONSTRAINT `fk_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`packages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`packages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`packages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_service_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_packages_company_service1_idx` (`company_service_id` ASC),
  CONSTRAINT `fk_packages_company_service1`
    FOREIGN KEY (`company_service_id`)
    REFERENCES `mydb`.`company_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_characteristics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service_characteristics` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service_characteristics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `type` INT NOT NULL,
  `service_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_idx` (`service_id` ASC),
  CONSTRAINT `fk_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`package_characteristics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`package_characteristics` ;

CREATE TABLE IF NOT EXISTS `mydb`.`package_characteristics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `package_id` INT NOT NULL,
  `characteristic_id` INT NOT NULL,
  `value` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_package_idx` (`package_id` ASC),
  INDEX `fk_characteristic_idx` (`characteristic_id` ASC),
  CONSTRAINT `fk_package`
    FOREIGN KEY (`package_id`)
    REFERENCES `mydb`.`packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characteristic`
    FOREIGN KEY (`characteristic_id`)
    REFERENCES `mydb`.`service_characteristics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`scrapers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`scrapers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`scrapers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_service_id` INT NOT NULL,
  `name` VARCHAR(127) NOT NULL,
  `url` VARCHAR(127) NOT NULL,
  `script_name` VARCHAR(127) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `last_updated` DATETIME NOT NULL,
  `error` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_scrapers_company_service1_idx` (`company_service_id` ASC),
  CONSTRAINT `fk_scrapers_company_service1`
    FOREIGN KEY (`company_service_id`)
    REFERENCES `mydb`.`company_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO hacktm;
 DROP USER hacktm;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'hacktm' IDENTIFIED BY 'hacktm';

GRANT ALL ON `mydb`.* TO 'hacktm';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
