-- MySQL Script generated by MySQL Workbench
-- 05/27/17 00:22:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hacktm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hacktm` ;

-- -----------------------------------------------------
-- Schema hacktm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hacktm` DEFAULT CHARACTER SET utf8 ;
USE `hacktm` ;

-- -----------------------------------------------------
-- Table `hacktm`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hacktm`.`companies` ;

CREATE TABLE IF NOT EXISTS `hacktm`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hacktm`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hacktm`.`services` ;

CREATE TABLE IF NOT EXISTS `hacktm`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hacktm`.`scrapers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hacktm`.`scrapers` ;

CREATE TABLE IF NOT EXISTS `hacktm`.`scrapers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NOT NULL,
  `url` VARCHAR(127) NOT NULL,
  `script_name` VARCHAR(127) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `last_updated` DATETIME NOT NULL,
  `error` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
KEY_BLOCK_SIZE = 4;


-- -----------------------------------------------------
-- Table `hacktm`.`company_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hacktm`.`company_service` ;

CREATE TABLE IF NOT EXISTS `hacktm`.`company_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companies_id` INT NOT NULL,
  `services_id` INT NOT NULL,
  `scrapers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_service_companies1_idx` (`companies_id` ASC),
  INDEX `fk_company_service_services1_idx` (`services_id` ASC),
  INDEX `fk_company_service_scrapers1_idx` (`scrapers_id` ASC),
  CONSTRAINT `fk_company_service_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `hacktm`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_service_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `hacktm`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_service_scrapers1`
    FOREIGN KEY (`scrapers_id`)
    REFERENCES `hacktm`.`scrapers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hacktm`.`bundles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hacktm`.`bundles` ;

CREATE TABLE IF NOT EXISTS `hacktm`.`bundles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `scrapers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bundles_scrapers1_idx` (`scrapers_id` ASC),
  CONSTRAINT `fk_bundles_scrapers1`
    FOREIGN KEY (`scrapers_id`)
    REFERENCES `hacktm`.`scrapers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hacktm`.`packages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hacktm`.`packages` ;

CREATE TABLE IF NOT EXISTS `hacktm`.`packages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_service_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL NOT NULL,
  `packagescol` VARCHAR(45) NULL,
  `bundles_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_packages_company_service1_idx` (`company_service_id` ASC),
  INDEX `fk_packages_bundles1_idx` (`bundles_id` ASC),
  CONSTRAINT `fk_packages_company_service1`
    FOREIGN KEY (`company_service_id`)
    REFERENCES `hacktm`.`company_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_packages_bundles1`
    FOREIGN KEY (`bundles_id`)
    REFERENCES `hacktm`.`bundles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hacktm`.`service_characteristics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hacktm`.`service_characteristics` ;

CREATE TABLE IF NOT EXISTS `hacktm`.`service_characteristics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `type` INT NOT NULL,
  `services_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_characteristics_services1_idx` (`services_id` ASC),
  CONSTRAINT `fk_service_characteristics_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `hacktm`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hacktm`.`package_characteristics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hacktm`.`package_characteristics` ;

CREATE TABLE IF NOT EXISTS `hacktm`.`package_characteristics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(1024) NOT NULL,
  `packages_id` INT NOT NULL,
  `service_characteristics_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_package_characteristics_packages1_idx` (`packages_id` ASC),
  INDEX `fk_package_characteristics_service_characteristics1_idx` (`service_characteristics_id` ASC),
  CONSTRAINT `fk_package_characteristics_packages1`
    FOREIGN KEY (`packages_id`)
    REFERENCES `hacktm`.`packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_package_characteristics_service_characteristics1`
    FOREIGN KEY (`service_characteristics_id`)
    REFERENCES `hacktm`.`service_characteristics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO hacktm;
 DROP USER hacktm;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'hacktm' IDENTIFIED BY 'hacktm';

GRANT ALL ON `hacktm`.* TO 'hacktm';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
